#!/bin/bash

set -e

export SERVICE_NAME=detox-dopamine
export PORT="4444"
export MONGO_URL="mongodb+srv://radientbrain:eLcXCPk6HkOVBHlw@cluster0.1pr7uy6.mongodb.net/test"

go test ./...
go build -tags=jsoniter -o build/detox-dopamine
./build/detox-dopamine
